# Generated by Django 5.2.3 on 2025-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='honba',
            field=models.PositiveIntegerField(default=0, verbose_name='積棒'),
        ),
        migrations.AddField(
            model_name='condition',
            name='kyotaku',
            field=models.PositiveIntegerField(default=0, verbose_name='供託'),
        ),
    ]
