# Generated by Django 5.2.3 on 2025-07-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSC', '0002_condition_honba_condition_kyotaku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='is_chiho',
        ),
    ]
