# Generated by Django 5.2.3 on 2025-07-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSC', '0002_remove_condition_is_tsumo_hand_is_tsumo'),
        ('MSC', '0003_remove_condition_is_chiho'),
    ]

    operations = [
    ]
