# Generated by Django 5.2.1 on 2025-07-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSC', '0004_merge_20250706_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='is_tsumo',
        ),
        migrations.AddField(
            model_name='condition',
            name='is_tsumo',
            field=models.BooleanField(default=True, verbose_name='ツモ和了'),
        ),
    ]
