# Generated by Django 5.2.1 on 2025-07-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSC', '0005_remove_hand_is_tsumo_condition_is_tsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='is_tsumo',
            field=models.BooleanField(default=True, verbose_name='ツモ和了'),
        ),
    ]
