# Generated by Django 5.2.2 on 2025-08-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSC', '0006_hand_is_tsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='winning_pai',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='和了牌'),
        ),
    ]
